-- Clears all business-data records, preserving users/roles/permissions/user_roles/
-- sub_agents/system_settings and Rails-internal solid_queue_*/solid_cache_entries tables.
-- Generated 2026-08-22 against db/schema.rb of ecommerce-store-dhanvatri.

BEGIN;

TRUNCATE TABLE
  active_storage_attachments,
  active_storage_blobs,
  active_storage_variant_records,
  affiliates,
  banners,
  booking_invoices,
  booking_items,
  bookings,
  booking_schedules,
  categories,
  client_requests,
  coupons,
  customer_addresses,
  customer_formats,
  customers,
  customer_wallets,
  delivery_charges,
  delivery_people,
  delivery_rules,
  device_tokens,
  documents,
  expenses,
  franchises,
  invoice_items,
  invoices,
  leads,
  milk_delivery_tasks,
  milk_subscriptions,
  notes,
  notifications,
  order_items,
  orders,
  pending_amounts,
  product_ratings,
  product_reviews,
  products,
  product_variants,
  referrals,
  sale_items,
  staff_attendances,
  staff_members,
  staff_payments,
  stock_batches,
  stock_movements,
  stock_transfers,
  stores,
  subscription_templates,
  vendor_invoices,
  vendor_payments,
  vendor_purchase_items,
  vendor_purchases,
  vendors,
  wallet_transactions,
  wishlists
RESTART IDENTITY CASCADE;

COMMIT;
