default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres:Dhan2026pg@localhost:5433/dhanvantari' %>
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres:Dhan2026pg@localhost:5433/dhanvantari' %>
  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres:Dhan2026pg@localhost:5433/dhanvantari' %>
  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres:Dhan2026pg@localhost:5433/dhanvantari' %>

test:
  primary:
    <<: *default
    url: postgresql://postgres:Dhan2026pg@localhost:5433/marali_sante_test
  cable:
    <<: *default
    url: postgresql://postgres:Dhan2026pg@localhost:5433/marali_sante_test
  queue:
    <<: *default
    url: postgresql://postgres:Dhan2026pg@localhost:5433/marali_sante_test
  cache:
    <<: *default
    url: postgresql://postgres:Dhan2026pg@localhost:5433/marali_sante_test

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres:Dhan2026pg@localhost:5433/dhanvantari' %>
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres:Dhan2026pg@localhost:5433/dhanvantari' %>
  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres:Dhan2026pg@localhost:5433/dhanvantari' %>
  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres:Dhan2026pg@localhost:5433/dhanvantari' %>
