default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://dhanva_2_user:s0PJMBrr7fUCAQUldxeoFWDQK0KKvn1B@dpg-d81sglg3kofs73c3jri0-a.oregon-postgres.render.com/dhanva_2' %>
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://dhanva_2_user:s0PJMBrr7fUCAQUldxeoFWDQK0KKvn1B@dpg-d81sglg3kofs73c3jri0-a.oregon-postgres.render.com/dhanva_2' %>
  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://dhanva_2_user:s0PJMBrr7fUCAQUldxeoFWDQK0KKvn1B@dpg-d81sglg3kofs73c3jri0-a.oregon-postgres.render.com/dhanva_2' %>
  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://dhanva_2_user:s0PJMBrr7fUCAQUldxeoFWDQK0KKvn1B@dpg-d81sglg3kofs73c3jri0-a.oregon-postgres.render.com/dhanva_2' %>

test:
  primary:
    <<: *default
    database: marali_sante_test
  cable:
    <<: *default
    database: marali_sante_test
  queue:
    <<: *default
    database: marali_sante_test
  cache:
    <<: *default
    database: marali_sante_test

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://dhanva_2_user:s0PJMBrr7fUCAQUldxeoFWDQK0KKvn1B@dpg-d81sglg3kofs73c3jri0-a.oregon-postgres.render.com/dhanva_2' %>
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://dhanva_2_user:s0PJMBrr7fUCAQUldxeoFWDQK0KKvn1B@dpg-d81sglg3kofs73c3jri0-a.oregon-postgres.render.com/dhanva_2' %>
  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://dhanva_2_user:s0PJMBrr7fUCAQUldxeoFWDQK0KKvn1B@dpg-d81sglg3kofs73c3jri0-a.oregon-postgres.render.com/dhanva_2' %>
  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://dhanva_2_user:s0PJMBrr7fUCAQUldxeoFWDQK0KKvn1B@dpg-d81sglg3kofs73c3jri0-a.oregon-postgres.render.com/dhanva_2' %>
    