default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://dr_wise_db:LuJjGp3KAMz8jsBiE9PKVzwU8InrN00H@dpg-daammph5efls738seqm0-a.oregon-postgres.render.com/markettincer_db_k4v1' %>
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://dr_wise_db:LuJjGp3KAMz8jsBiE9PKVzwU8InrN00H@dpg-daammph5efls738seqm0-a.oregon-postgres.render.com/markettincer_db_k4v1' %>
  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://dr_wise_db:LuJjGp3KAMz8jsBiE9PKVzwU8InrN00H@dpg-daammph5efls738seqm0-a.oregon-postgres.render.com/markettincer_db_k4v1' %>
  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://dr_wise_db:LuJjGp3KAMz8jsBiE9PKVzwU8InrN00H@dpg-daammph5efls738seqm0-a.oregon-postgres.render.com/markettincer_db_k4v1' %>

test:
  primary:
    <<: *default
    url: postgresql://postgres:Dhan2026pg@localhost:5433/marali_sante_test
  cable:
    <<: *default
    url: postgresql://postgres:Dhan2026pg@localhost:5433/marali_sante_test
  queue:
    <<: *default
    url: postgresql://postgres:Dhan2026pg@localhost:5433/marali_sante_test
  cache:
    <<: *default
    url: postgresql://postgres:Dhan2026pg@localhost:5433/marali_sante_test

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres:Dhan2026pg@localhost:5433/dhanvantari' %>
  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres:Dhan2026pg@localhost:5433/dhanvantari' %>
  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres:Dhan2026pg@localhost:5433/dhanvantari' %>
  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] || 'postgresql://postgres:Dhan2026pg@localhost:5433/dhanvantari' %>
